"""Add new table

Revision ID: 9552b9fc884a
Revises: 9e858906b135
Create Date: 2025-05-10 23:29:29.420332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9552b9fc884a'
down_revision: Union[str, None] = '9e858906b135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_user_company', sa.Column('role_name', sa.String(length=256), nullable=False))
    op.create_foreign_key(None, 'association_user_company', 'role', ['company_id', 'role_name'], ['company_id', 'name'], ondelete='CASCADE')
    op.drop_column('association_user_company', 'user_level')
    op.alter_column('company', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('company', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('company', 'industry',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('company', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('company', 'phone_number',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'phone_number',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('company', 'email',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('company', 'industry',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('company', 'description',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('company', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('association_user_company', sa.Column('user_level', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'association_user_company', type_='foreignkey')
    op.drop_column('association_user_company', 'role_name')
    # ### end Alembic commands ###
